### ISSUE TITLE
Allow instructors to specify point value (or weight) for individual exercises within an assignment.

### ISSUE THREAD

**Issue by srp33** [srp33/CodeBuddy#105]

**Comment by srp33** [comment]
@pjtatlow Just implemented this. Each exercise has a weight of 1.0 by default. You can assign a higher or lower weight, and that influences the overall assignment score. Does that work for your needs? Would you use it this semester if I push this to production? Or are you okay to wait?

**Comment by pjtatlow** [comment]
@srp33 Sorry for the super late response, but that sounds perfect for what I need. I probably won't use it until next semester though, so no need to ship it soon!
