### ISSUE TITLE
When assignment times out, students can still see the exercise page (and the timer values are negative) in studio mode

### ISSUE THREAD

**Issue by srp33** [srp33/CodeBuddy#111]
The timer looks good! But it's keeping me on the exercise page after the time expires. It seems like the page is getting refreshed periodically, so maybe it's redirecting to the wrong URL? @pjtatlow 

<img width="1665" alt="image" src="https://user-images.githubusercontent.com/12720/192621936-fe18c5f3-3ab0-4ab9-83bb-5806d20a10eb.png">

**Comment by pjtatlow** [comment]
I had it just refreshing the page because it was taking me to an error page that said my time was up. There seems to be an issue with the `has_user_assignment_start_timer_ended` function, because it isn't returning true for me, which is allowing them to load the exercise page even though their time is up. Seems to be a timezone issue maybe?

**Comment by pjtatlow** [comment]
For example, my 1 minute timer has expired, but when I print `curr_time` and `start_time` I get these values:
curr_time = `2022-09-28 12:31:34.019378`
start_time = `2022-09-28 18:21:12`

**Comment by pjtatlow** [comment]
That PR makes studio mode do the redirect like it's supposed to, but I think we need to figure out this other issue, because when I go back to the assignments page, it says I have zero time left but it still lets me to go each exercise for like one second before redirecting me back.

**Comment by srp33** [comment]
Thanks for letting me know. I'm working on fixing the time-zone issue.

**Comment by srp33** [comment]
I'm still figuring out the timer issue. It's a bit of a mess. I haven't had
as much time this week, but I'll get back to you as soon as I can.

**Comment by pjtatlow** [comment]
No worries, I’m not using the timer feature for my class 😂

**Comment by srp33** [comment]
I know. I just have to make sure it's working perfectly before going to
production because I am delivering a timed exam next week.

**Comment by pjtatlow** [comment]
Let me know if there is anything I can do to help get this done!

**Comment by srp33** [comment]
Thanks! I have needed to put time into another project, but I was able to
figure out the timer issues, I believe. Now I'm making sure the due date
functionality works. Hopefully I'll have it ready soon.
