### ISSUE TITLE
Deleting presubmissions

### ISSUE THREAD

**Issue by srp33** [srp33/CodeBuddy#112]
The auto-save feature seems to be working beautifully.

Are we using the presubmissions table to save code? If so, do we have a process for clearing that table? One place we can do this (to some extent) is In server/handlers/SubmitHandler.py. On line 34, we are deleting those after we submit. That is probably not the best way to do it though. I'm sure you've got this covered but just wanted to check with you. @pjtatlow

**Comment by pjtatlow** [comment]
Why do we need to clear the pre submissions table?

**Comment by srp33** [comment]
My thought was to save space in the database. However, if we only save one
row per student per exercise (is that the case?), then maybe it's not a big
deal. We can just delete them when we "purge" submissions. What do you
think?

**Comment by pjtatlow** [comment]
Yeah it's only one per student per exercise, they'll take up much less space than the actual submissions. I like that idea of purging them with submissions. When does that happen? When you delete the exercise?

**Comment by srp33** [comment]
There are Purge buttons on the course_admin and assignment_admin page. I'll
add a ticket to remind me to make sure those get deleted.
