### ISSUE TITLE
Remove empty scroll bar in navigation menu

### ISSUE THREAD

**Issue by srp33** [srp33/CodeBuddy#113]
It scrolls when there are many entries. When there are not, it still shows an empty scroll bar.

**Comment by srp33** [comment]
@pjtatlow Would you mind looking at this one? I know you changed the navbar dropdowns so they would scroll when there are a lot of entries (thus addressing the white-space issue we were seeing). However, when it doesn't need to scroll, there is an empty scroll bar showing. I was going to look at this but thought you might be able to fix it more quickly than I would. Would you please take a look?

**Comment by pjtatlow** [comment]
I'm not seeing scroll bars on my end, do you by chance have this enabled on your Mac? 
<img width="452" alt="image" src="https://user-images.githubusercontent.com/4894249/196539444-bfb16c58-469c-4d37-9253-c66ff743405c.png">

**Comment by srp33** [comment]
Aha! Yes, I do. Thank you!
