### ISSUE TITLE
Ability to download your code as a student

### ISSUE THREAD

**Issue by pjtatlow** [srp33/CodeBuddy#142]
At the end of a semester, some students want to be able to access their code for reference, but we probably don't want to keep it on CodeBuddy forever. Would be nice to have a way to download it all, with nice file names, as a `.zip` or something.

**Comment by srp33** [comment]
Students have been asking for this since the beginning of CodeBuddy. It would be nice to finally provide it as an option.

**Comment by srp33** [comment]
Basic functionality has been added. But need to rework it slightly after we address #140 . Instead of excluding timed assignments, exclude based on a flag that indicates whether each assignment is an exam.
