### ISSUE TITLE
Unable to open database file

### ISSUE THREAD

**Issue by KleinSamuel** [srp33/CodeBuddy#267]
Hello :)

I am trying to run the CodeBuddy on a Linux x86_64 machine.
The repository was cloned from master branch and the configuration was performed as stated in the README.
When the run_front_end script is executed, the following error occurs:

```
Successfully built 137c79edb61c
Successfully tagged codebuddy/front_end_development:version46
Successfully tagged codebuddy/front_end_development:latest
Summarizing log files [Thu Sep  7 12:14:33 UTC 2023]...
Done summarizing log files [Thu Sep  7 12:14:34 UTC 2023]...
Starting front-end server...
Current database version: 15
Current code version: 46
Checking database status for version 16...
Database migration failed for version 16...
Traceback (most recent call last):
  File "/app/migration_scripts/15_to_16.py", line 18, in <module>
    content = Content(settings_dict)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/app/./server/content.py", line 29, in __init__
    self.conn = open_db(db_file_path)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/app/./server/helper.py", line 451, in open_db
    return sqlite3.connect(
           ^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file
```

I tried both modes, development and production.

Thanks for your help and let me know if you need more information.

**Comment by KleinSamuel** [comment]
Apparently this happens because in the scripts under `front_end/migration_scripts/` (for example `15_to_16.py`) the `Content()` object is created with the `settings_dict` variable which contains a dict of settings from the `/home/sam/Projects/CodeBuddy/Settings.yaml` file but it expects a string that contains the path to a `.db` sqlite database file.

When I delete the `settings_dict` parameter then the default database path is used and no error occurs.

This also happens in the other `X_to_Y.py` scripts.

**Comment by srp33** [comment]
Hi @KleinSamuel, thanks for your interest in CodeBuddy and thanks for letting me know about this issue. I just fixed it, I believe. Please pull the latest version and try running the front end again. I tested it on my side, but if you could please let me know how it goes on your side, that would be great.

**Comment by KleinSamuel** [comment]
Thank you for the fast response and action!
The error does not occur in the latest version anymore.
