### ISSUE TITLE
Can't work on assignments after exam concluded

### ISSUE THREAD

**Issue by samhatty** [srp33/CodeBuddy#294]
I just took an exam through examity and used code buddy to submit my work. Now I am trying to do an assignment but it is not allowing me to because "You are currently taking a timed assignment, and the instructor has restricted access to all other assignments while you are taking it." even though I am done with the exam. Is there a way that you can stop the exams that are active on codebuddy?

**Comment by srp33** [comment]
@samhatty Thanks for the feedback! This is a known issue. https://github.com/srp33/CodeBuddy/issues/266

I'll try to get to it soon!
