### ISSUE TITLE
error: front-end server was unable to contact the back-end server

### ISSUE THREAD

**Issue by sllarson2005** [srp33/CodeBuddy#303]
I'm not sure what this error is coming from, I've tried different devices and browsers and keep receiving it. My wifi is working and have tried re-running old codes that previously worked and am now getting the error message on those as well. What is the issue causing the "error: front-end server was unable to contact the back-end server" message and what can I do to fix it?

**Comment by srp33** [comment]
@sllarson2005 Has it worked previously? Or are you trying to get it running for the first time?

Is the "run_middle_layer" script running?

**Comment by srp33** [comment]
I just updated the instructions to try to clarify some things in addition to my comment above. Please let me know how it goes.

**Comment by sllarson2005** [comment]
The code ran before and code buddy showed which tests passed and which were not. I'm not sure how to check if the "run_middle_layer" script is running, where could I check that?

**Comment by srp33** [comment]
Sorry, I misunderstood that you are a student. Please try it again now.
