### ISSUE TITLE
KeyError: 'test_outputs'

### ISSUE THREAD

**Issue by Shinoa8** [srp33/CodeBuddy#311]
Hey!!!

I am trying to run the CodeBuddy on a Windows.
I did all the steps according to the README.
When i Edit exercise this error occurs:

```
Traceback (most recent call last):
File "/home/alibek/CodeBuddy/CodeBuddy/front_end/server/handlers/EditExerciseHandler.py", Line 57, in post
result, success = await execute and_save_exercise(self.settings dict, self.content, exercise_basics, exercise details)
File "/home/alibek/CodeBuddy/CodeBuddy/front_end/server/helper.py", line 489, in execute_and_save_exercise
exec_response = await exec_code(settings_dict, exercise details[ "solution_code"].
"", exercise _details, True)
File "/home/alibek/CodeBuddy/CodeBuddy/front|
end/server/helper.py*, line 176, in exec_code
for test_title in responsel "test_outputs"]:
KeyError: 'test_outputs'
```

**Comment by Shinoa8** [comment]
![WhatsApp Image 2024-03-10 at 18 23 50_1921fe26](https://github.com/srp33/CodeBuddy/assets/124333084/212f3cd8-97e4-46be-a5b8-09abec177a5b)

**Comment by Shinoa8** [comment]
@srp33 I Need Help.......

**Comment by srp33** [comment]
Thanks for your patience. It was the weekend for me, and I was with family...

Earlier you submitted an issue with an error message saying "sqlite3.OperationalError: unable to open database file". Did that get resolved?

If you open the VERSION file, what number does it have in it?

**Comment by Shinoa8** [comment]
Thank you for the response.. The other error i managed to solved. The version is 50. Websites is launched and when i goto course and then goto edit exercise and submit everything with python as backend it give me error of key error test_outputs. But with python_testing_script no error save successfully

**Comment by srp33** [comment]
Are you running the back end server? You would need to execute bash run_middle_layer.

**Comment by Shinoa8** [comment]
Yes bash run_middle_layer working at the back

**Comment by Shinoa8** [comment]
This the error i am facing in edit exercise screen: 

'''
Traceback (most recent call last):
File "/home/alibek/CodeBuddy/CodeBuddy/front_end/server/handlers/EditExerciseHandler.py", Line 57, in post
result, success = await execute and_save_exercise(self.settings dict, self.content, exercise_basics, exercise details)
File "/home/alibek/CodeBuddy/CodeBuddy/front_end/server/helper.py", line 489, in execute_and_save_exercise
exec_response = await exec_code(settings_dict, exercise details[ "solution_code"].
"", exercise _details, True)
File "/home/alibek/CodeBuddy/CodeBuddy/front|
end/server/helper.py*, line 176, in exec_code
for test_title in responsel "test_outputs"]:
KeyError: 'test_outputs'
'''

**Comment by Shinoa8** [comment]
And when i print response this is what is get:

```
{'detail: [type': dict_type', 'loc': ['body, 'data_files], 'msg: Input should be a valid dictionary, 'input: I. 'ur!: 'https://errors.pydantic.dev/
2.6/v/dict_type }]
```

**Comment by srp33** [comment]
I have an idea what might be happening. To narrow it down, please do the following:

1. Stop the run_front_end and run_middle_layer scripts.
2. Use `git pull` to pull the latest version of the code.
3. Start the front end and middle layer.

Let me know what error you are getting after that.

**Comment by Shinoa8** [comment]
So my run_front_end is not working doing it in ubuntu this is the error i get in ubuntu:

```
Step 23/39 : RUN groupadd - -g $/GROUP
LD} SUSER) &&
(USER) &&
chown --silent --ne-dereference -recursive
-> Running in eafbb31882e8 useradd: UID 0 is not unique
The command '/bin/sh -c groupadd -f -g $(GROUP_ID) S(USER) && home/S[USER} && chown -silent -ne-dereference -recursive tmp' returned a non-zero code: 4
useradd -I -u $(USER_ID} -g $(USER) $(USER) && install-d -m 0755 -0 S(USER) -g S(USER} /home/$
S(USER_ID):$(GROUP_ID}
/app /conda /course /migration_scripts /static /scheduled_scripts /tmp
useradd 1 -u S(USER_ID) -g S(USER) S(USER) && install -d -m 0755 -0 S(USER) -g S(USER) /
S(USER_ID):S(GROUP_ID}
/app /conda /course /migration_scripts /static /scheduled_scripts /
```

and when i run the run_front_end on windows in docker i got this error:
![WhatsApp Image 2024-03-10 at 18 40 18_6e913f3d](https://github.com/srp33/CodeBuddy/assets/124333084/6a671c59-a130-4776-84c5-4bc0253a3deb)

**Comment by Shinoa8** [comment]
I am runing my front end directly without the run_front_end.

**Comment by srp33** [comment]
Did you complete the steps that I requested? I thought you were running on a Windows computer?

**Comment by srp33** [comment]
Please first work on getting it running within Docker. Please follow the steps on the README page from the beginning. If you get an error, please tell me the step where you saw the error.

**Comment by Shinoa8** [comment]
I first follow all the steps and run it with docker when the run_front_end is completed i goto docker and i run it it gives me this error: 
![WhatsApp Image 2024-03-10 at 18 40 18_932cd79f](https://github.com/srp33/CodeBuddy/assets/124333084/d60128d5-d4bd-42fb-8d8b-854bfd510944)

**Comment by srp33** [comment]
This looks like Windows now. Are you using Windows or Ubuntu? Which terminal are you using when you run the command? What is your working directory?

**Comment by Shinoa8** [comment]
This is windows and i am running vs code terminal

**Comment by srp33** [comment]
The instructions say, "If you are using a Windows operating system, install git for windows. Then open Git Bash and use that as your terminal." Please do that and let me know your working directory (`pwd` command) where you are executing `run_front_end`.

**Comment by Shinoa8** [comment]
My current working dir:
```
/c/CodeBuddy-master
```
And after running the ```run_front_end``` it says 
```
Done updating database to version 50 
```
and nothing else on terminal

**Comment by srp33** [comment]
If you see nothing else on the terminal, it suggests that it's working. What happens when you open it in your Web browser for the specified port?

**Comment by Shinoa8** [comment]
Nothing  ```127.0.0.1 refused to connect.``` no port working

**Comment by Shinoa8** [comment]
So my back end is running 

![image](https://github.com/srp33/CodeBuddy/assets/124333084/e88bf86a-6130-4c74-885a-b27971ac9fb7)

but front end is giving this error on git bash 
![image](https://github.com/srp33/CodeBuddy/assets/124333084/59481bed-d397-4e78-bd4d-debaa5e35149)

``` run_front_end``` Works on vs terminal but give the following error on gitbash

**Comment by srp33** [comment]
Oh okay. If it works on VS terminal, that's great. Is it working overall now?

**Comment by Shinoa8** [comment]
No the ~~~run_front_end~~~ file runs on vscode but do nothing backend file is running but no website on web browser

**Comment by srp33** [comment]
Which port is listed in Settings.yaml under f_port?

What URL are you using to try to access it?

**Comment by Shinoa8** [comment]
default settings 
f_port 8008
Url 127.0.0.1:8008

**Comment by srp33** [comment]
Was it working previously on that port? Or was that on a different computer / operating system?

**Comment by Shinoa8** [comment]
The code never works with run_front_end
It works if we manually run the make file and that will run webserver.py on localhost:8008

**Comment by Shinoa8** [comment]
Also if front end and back end is running then what to do? What to type in browser in order to see there website?

**Comment by srp33** [comment]
Today is very busy for me. But perhaps tomorrow we could jump on a Zoom call to figure it out?

**Comment by Shinoa8** [comment]
Okk perfect..
